<?php

use Illuminate\Database\Seeder;
use App\Industry;

class IndustrySeeder extends Seeder
{
    protected $industries = array(
        array('id' => '1','title' => 'Defense & Space'),
        array('id' => '3','title' => 'Computer Hardware'),
        array('id' => '4','title' => 'Computer Software'),
        array('id' => '5','title' => 'Computer Networking'),
        array('id' => '6','title' => 'Internet'),
        array('id' => '7','title' => 'Semiconductors'),
        array('id' => '8','title' => 'Telecommunications'),
        array('id' => '9','title' => 'Law Practice'),
        array('id' => '10','title' => 'Legal Services'),
        array('id' => '11','title' => 'Management Consulting'),
        array('id' => '12','title' => 'Biotechnology'),
        array('id' => '13','title' => 'Medical Practice'),
        array('id' => '14','title' => 'Hospital & Health Care'),
        array('id' => '15','title' => 'Pharmaceuticals'),
        array('id' => '16','title' => 'Veterinary'),
        array('id' => '17','title' => 'Medical Devices'),
        array('id' => '18','title' => 'Cosmetics'),
        array('id' => '19','title' => 'Apparel & Fashion'),
        array('id' => '20','title' => 'Sporting Goods'),
        array('id' => '21','title' => 'Tobacco'),
        array('id' => '22','title' => 'Supermarkets'),
        array('id' => '23','title' => 'Food Production'),
        array('id' => '24','title' => 'Consumer Electronics'),
        array('id' => '25','title' => 'Consumer Goods'),
        array('id' => '26','title' => 'Furniture'),
        array('id' => '27','title' => 'Retail'),
        array('id' => '28','title' => 'Entertainment'),
        array('id' => '29','title' => 'Gambling & Casinos'),
        array('id' => '30','title' => 'Leisure, Travel & Tourism'),
        array('id' => '31','title' => 'Hospitality'),
        array('id' => '32','title' => 'Restaurants'),
        array('id' => '33','title' => 'Sports'),
        array('id' => '34','title' => 'Food & Beverages'),
        array('id' => '35','title' => 'Motion Pictures and Film'),
        array('id' => '36','title' => 'Broadcast Media'),
        array('id' => '37','title' => 'Museums and Institutions'),
        array('id' => '38','title' => 'Fine Art'),
        array('id' => '39','title' => 'Performing Arts'),
        array('id' => '40','title' => 'Recreational Facilities and Services'),
        array('id' => '41','title' => 'Banking'),
        array('id' => '42','title' => 'Insurance'),
        array('id' => '43','title' => 'Financial Services'),
        array('id' => '44','title' => 'Real Estate'),
        array('id' => '45','title' => 'Investment Banking'),
        array('id' => '46','title' => 'Investment Management'),
        array('id' => '47','title' => 'Accounting'),
        array('id' => '48','title' => 'Construction'),
        array('id' => '49','title' => 'Building Materials'),
        array('id' => '50','title' => 'Architecture & Planning'),
        array('id' => '51','title' => 'Civil Engineering'),
        array('id' => '52','title' => 'Aviation & Aerospace'),
        array('id' => '53','title' => 'Automotive'),
        array('id' => '54','title' => 'Chemicals'),
        array('id' => '55','title' => 'Machinery'),
        array('id' => '56','title' => 'Mining & Metals'),
        array('id' => '57','title' => 'Oil & Energy'),
        array('id' => '58','title' => 'Shipbuilding'),
        array('id' => '59','title' => 'Utilities'),
        array('id' => '60','title' => 'Textiles'),
        array('id' => '61','title' => 'Paper & Forest Products'),
        array('id' => '62','title' => 'Railroad Manufacture'),
        array('id' => '63','title' => 'Farming'),
        array('id' => '64','title' => 'Ranching'),
        array('id' => '65','title' => 'Dairy'),
        array('id' => '66','title' => 'Fishery'),
        array('id' => '67','title' => 'Primary/Secondary Education'),
        array('id' => '68','title' => 'Higher Education'),
        array('id' => '69','title' => 'Education Management'),
        array('id' => '70','title' => 'Research'),
        array('id' => '71','title' => 'Military'),
        array('id' => '72','title' => 'Legislative Office'),
        array('id' => '73','title' => 'Judiciary'),
        array('id' => '74','title' => 'International Affairs'),
        array('id' => '75','title' => 'Government Administration'),
        array('id' => '76','title' => 'Executive Office'),
        array('id' => '77','title' => 'Law Enforcement'),
        array('id' => '78','title' => 'Public Safety'),
        array('id' => '79','title' => 'Public Policy'),
        array('id' => '80','title' => 'Marketing and Advertising'),
        array('id' => '81','title' => 'Newspapers'),
        array('id' => '82','title' => 'Publishing'),
        array('id' => '83','title' => 'Printing'),
        array('id' => '84','title' => 'Information Services'),
        array('id' => '85','title' => 'Libraries'),
        array('id' => '86','title' => 'Environmental Services'),
        array('id' => '87','title' => 'Package/Freight Delivery'),
        array('id' => '88','title' => 'Individual & Family Services'),
        array('id' => '89','title' => 'Religious Institutions'),
        array('id' => '90','title' => 'Civic & Social Organization'),
        array('id' => '91','title' => 'Consumer Services'),
        array('id' => '92','title' => 'Transportation/Trucking/Railroad'),
        array('id' => '93','title' => 'Warehousing'),
        array('id' => '94','title' => 'Airlines/Aviation'),
        array('id' => '95','title' => 'Maritime'),
        array('id' => '96','title' => 'Information Technology and Services'),
        array('id' => '97','title' => 'Market Research'),
        array('id' => '98','title' => 'Public Relations and Communications'),
        array('id' => '99','title' => 'Design'),
        array('id' => '100','title' => 'Non-Profit Organization Management'),
        array('id' => '101','title' => 'Fund-Raising'),
        array('id' => '102','title' => 'Program Development'),
        array('id' => '103','title' => 'Writing and Editing'),
        array('id' => '104','title' => 'Staffing and Recruiting'),
        array('id' => '105','title' => 'Professional Training & Coaching'),
        array('id' => '106','title' => 'Venture Capital & Private Equity'),
        array('id' => '107','title' => 'Political Organization'),
        array('id' => '108','title' => 'Translation and Localization'),
        array('id' => '109','title' => 'Computer Games'),
        array('id' => '110','title' => 'Events Services'),
        array('id' => '111','title' => 'Arts and Crafts'),
        array('id' => '112','title' => 'Electrical/Electronic Manufacturing'),
        array('id' => '113','title' => 'Online Media'),
        array('id' => '114','title' => 'Nanotechnology'),
        array('id' => '115','title' => 'Music'),
        array('id' => '116','title' => 'Logistics and Supply Chain'),
        array('id' => '117','title' => 'Plastics'),
        array('id' => '118','title' => 'Computer & Network Security'),
        array('id' => '119','title' => 'Wireless'),
        array('id' => '120','title' => 'Alternative Dispute Resolution'),
        array('id' => '121','title' => 'Security and Investigations'),
        array('id' => '122','title' => 'Facilities Services'),
        array('id' => '123','title' => 'Outsourcing/Offshoring'),
        array('id' => '124','title' => 'Health, Wellness and Fitness'),
        array('id' => '125','title' => 'Alternative Medicine'),
        array('id' => '126','title' => 'Media Production'),
        array('id' => '127','title' => 'Animation'),
        array('id' => '128','title' => 'Commercial Real Estate'),
        array('id' => '129','title' => 'Capital Markets'),
        array('id' => '130','title' => 'Think Tanks'),
        array('id' => '131','title' => 'Philanthropy'),
        array('id' => '132','title' => 'E-Learning'),
        array('id' => '133','title' => 'Wholesale'),
        array('id' => '134','title' => 'Import and Export'),
        array('id' => '135','title' => 'Mechanical or Industrial Engineering'),
        array('id' => '136','title' => 'Photography'),
        array('id' => '137','title' => 'Human Resources'),
        array('id' => '138','title' => 'Business Supplies and Equipment'),
        array('id' => '139','title' => 'Mental Health Care'),
        array('id' => '140','title' => 'Graphic Design'),
        array('id' => '141','title' => 'International Trade and Development'),
        array('id' => '142','title' => 'Wine and Spirits'),
        array('id' => '143','title' => 'Luxury Goods & Jewelry'),
        array('id' => '144','title' => 'Renewables & Environment'),
        array('id' => '145','title' => 'Glass, Ceramics & Concrete'),
        array('id' => '146','title' => 'Packaging and Containers'),
        array('id' => '147','title' => 'Industrial Automation'),
        array('id' => '148','title' => 'Government Relations')
      );
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        try{
            foreach($this->industries as $industry){
                $model = Industry::firstOrNew([
                    'title' => $industry['title']
                ]);
                $model->save();
            }
        }catch(Illuminate\Database\QueryException $e){
            return false;
        }
    }
}
